# Error propagation for normalized uncertainties

Consider an observable $x$ and its covariance matrix $\Sigma_x$. The generalized covariance transformation is $\Sigma_y = J \Sigma_x J^T$ where $J$ is the Jacobian matrix:

$J = 
\begin{bmatrix} 
\partial f_0 / \partial x_0 & \partial f_0 / \partial x_1 & \ldots \\
\partial f_1 / \partial x_0 & \partial f_1 / \partial x_1 & \ldots \\
\ldots & & \\
\end{bmatrix}$

Now consider a transformation of $x$ to normalize it: 

$y = \frac{x}{ \sum_i x_i} \equiv \frac{x}{N}$


Then the Jacobian is

$J = 
\begin{bmatrix} 
\frac{N-x_0}{N^2}  & \frac{-x_0}{N^2} & \frac{-x_0}{N^2} & \ldots \\
\frac{-x_1}{N^2} & \frac{N-x_1}{N^2} & \frac{-x_1}{N^2} & \ldots \\
\ldots 
\end{bmatrix}$


Coordinate transformations change the uncertainties as

$\sigma_y^2 = J \sigma_x^2 J^T$, 

where $\sigma_x$ is the covariance matrix, and $y$ is defined above. 

In [1]:
import numpy as np

### Define the normalized function and the Jacobian

In [2]:

def yf_jac( x ):
    N = np.sum(x)
    y = x / N    
    J = np.array([
        [ (N-x[0]) / N**2 , -x[0]/N**2, -x[0]/N**2],
        [-x[1]/N**2, (N-x[1]) / N**2 , -x[1]/N**2],
        [-x[2]/N**2, -x[2]/N**2, (N-x[2]) / N**2],
        ])
    return J 

#### Concrete example

$x = [ 100, 100, 400 ] $

$\sigma_x^2 = [100, 100, 400] $

(that is, statistical uncertainties like $\sqrt{N}$)

In [4]:

x = np.array( [100., 100., 400.] )
N = np.sum(x)
y = x/N
covx = np.zeros( (x.size, x.size) )
covx[0,0] = 100.
covx[1,1] = 100.
covx[2,2] = 400.

print("x = ", x)
print("y = ", y)

x =  [100. 100. 400.]
y =  [0.16666667 0.16666667 0.66666667]


#### Get covariance matrix in y

We then obtain the Jacobian and the covariance for $y$, where

$\sigma_y^2 = J \sigma_x^2 J^T$

In [5]:

jac = yf_jac(x)
covy = jac * covx * jac.T

#### Get the uncertainties in $x$ and $y$

In [8]:

print('jac :\n', jac)
print('covx:\n', covx)
print('covy:\n', covy)
dx = np.array( [np.sqrt(covx[i,i] ) for i in range(3)] )
dy = np.array( [np.sqrt(covy[i,i] ) for i in range(3)] )
dx2 = np.sqrt( y * (1-y) / N)
print('dx   : ', dx)
print('dy   : ', dy)
print('dx/x : ', dx/x)
print('dy/y : ', dy/y)

jac :
 [[ 0.00138889 -0.00027778 -0.00027778]
 [-0.00027778  0.00138889 -0.00027778]
 [-0.00111111 -0.00111111  0.00055556]]
covx:
 [[100.   0.   0.]
 [  0. 100.   0.]
 [  0.   0. 400.]]
covy:
 [[0.0001929  0.         0.        ]
 [0.         0.0001929  0.        ]
 [0.         0.         0.00012346]]
dx   :  [10. 10. 20.]
dy   :  [0.01388889 0.01388889 0.01111111]
dx/x :  [0.1  0.1  0.05]
dy/y :  [0.08333333 0.08333333 0.01666667]
